[serve]
port = 3000

[tools]
sass = "1.50.0"

[[proxy]]
# This proxy specifies only the backend, which is the only required field. In this example,
# request URIs are not modified when proxied.
backend = "https://yew.rs/tutorial"